apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksctl-cluster
  region: us-east-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.micro
    desiredCapacity: 4 # Adjusted to match minSize
    minSize: 4
    maxSize: 6
    volumeSize: 20
    volumeType: gp3
    ssh:
      allow: false
    labels:
      lifecycle: OnDemand
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true

  - name: nodegroup-2
    instanceType: t3.micro
    desiredCapacity: 4 # Adjusted to match minSize
    minSize: 4
    maxSize: 6
    privateNetworking: true
    volumeSize: 20
    volumeType: gp3
    ssh:
      allow: false
    labels:
      lifecycle: OnDemand
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - "api"
      - "audit"
      - "authenticator"
      - "controllerManager"
      - "scheduler"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
    - metadata:
        name: external-dns-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  - name: efs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
  - name: s3-csi-driver
    version: latest
  - name: eks-pod-identity-webhook
    version: latest

managedNodeGroups:
  - name: managed-nodegroup-1
    instanceType: t3.micro
    minSize: 4
    maxSize: 6
    desiredCapacity: 4
    privateNetworking: true
    labels:
      lifecycle: ec2-autoscaler
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
