apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksctl-cluster
  region: us-east-1
  tags:
    karpenter.sh/discovery: eksctl-cluster

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 6
    volumeSize: 20
    volumeType: gp3
    ssh:
      allow: false
    labels:
      lifecycle: OnDemand
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true

  - name: nodegroup-2
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 6
    privateNetworking: true
    volumeSize: 20
    volumeType: gp3
    ssh:
      allow: false
    labels:
      lifecycle: OnDemand
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - "api"
      - "audit"
      - "authenticator"
      - "controllerManager"
      - "scheduler"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
    - metadata:
        name: external-dns
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

karpenter:
  version: "v0.20.0"
  createServiceAccount: true
  withSpotInterruptionQueue: true

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
  - name: aws-efs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
  - name: aws-mountpoint-s3-csi-driver
    version: latest
  - name: eks-pod-identity-agent
    version: latest

managedNodeGroups:
  - name: managed-nodegroup-spot
    instanceTypes:
      ["t3.medium", "t3a.medium", "m5.large", "c5.large", "c5a.large"]
    desiredCapacity: 2
    minSize: 1
    maxSize: 6
    privateNetworking: true
    spot: true
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
